### ISSUE TITLE
Mods in plan

### ISSUE THREAD

**Issue by Aero-Seira** [Aerolaxy/HAD-Modded-Nutrients-Config#1]
- [x] Aether Delight
- [x] Alex's Delight
- [x] Aquaculture Delight 
- [x] Barbeque's Delight
- [x] Brewin and Chewin
- [x] Caupona
- [x] Convivium
- [x] Crabber's Delight
- [x] Create Cafe
- [x] Create Deepfried
- [x] Create Ratatouille
- [x] Crock Pot
- [x] Delightful
- [x] End's Delight
- [x] Ender's Delight
- [x] Maturi Delight
- [x] Nether's Delight
- [x] Ocean's Delight
- [x] Seasonals
- [x] Silent's Delight
- [x] The Aether
- [x] The Aether Redux
- [x] Twilight Flavors & Delight
- [x] Undergarden Delight 
- [x] Unusual Delight
- [x] Vintage Delight
- [x] Youkai's Homecoming

**Comment by ANGJustinl** [comment]
- [ ] Aether Delight
- [ ] Alex's Delight
- [ ] Aquaculture Delight 
- [ ] Barbeque's Delight
- [ ] Brewin and Chewin
- [ ] Caupona
- [ ] Convivium
- [ ] Crabber's Delight
- [ ] Create Cafe
- [ ] Create Deepfried
- [ ] Create Ratatouille
- [ ] Crock Pot
- [ ] Delightful
- [ ] End's Delight
- [ ] Ender's Delight
- [ ] Maturi Delight
- [ ] Nether's Delight
- [ ] Ocean's Delight
- [ ] Seasonals
- [ ] Silent's Delight
- [ ] The Aether
- [ ] The Aether Redux
- [ ] Twilight Flavors & Delight
- [ ] Undergarden Delight 
- [ ] Unusual Delight
- [ ] Vintage Delight
- [ ] Youkai's Homecoming

**Comment by ANGJustinl** [comment]
更改顺序

**Comment by ANGJustinl** [comment]
- [x] 提问 corn_delight 无需添加
- [x]  festival_delight
- [x]  miner_
